In [1]:
## Script to analyze Turbo Typing data

In [2]:
import os
import numpy as np
import pandas as pd
import math
import glob

In [3]:
# Setting save directory
save_dir = os.getcwd()
save_dir

'/Users/rubi/Desktop/Github/typingexp/typing_task_analysis'

In [57]:
# Getting subject data folders from server
server = r'/Volumes/greenhouse/typingtask_data/subject_data'
os.chdir(server)
folders = os.listdir()

# Looping through subject folders, getting appropriate paths to data, 
# and making sID list
sub_folders = list(filter(lambda x: x.startswith('s', 0, 1), folders))
all_turbo = pd.DataFrame()
ID_list = []
for sub in sub_folders:
    sub_folder = r'/Volumes/greenhouse/typingtask_data/'\
                 'subject_data/%s/turbotyping_data' % sub
    os.chdir(sub_folder)
    sID = sub.split('_', 1)[0]
    turbo = pd.read_csv(glob.glob('*_datafile.tsv')[0], sep='\t')
    all_turbo = pd.concat([all_turbo, turbo])
    ID_list.append(sID)

In [60]:
all_turbo

,participantID,trialNumber,currentSentence,typedSentence,trialStart,wpm,accuracy,timeData,keyData,keyDataConverted,timeDataUp,keyDataUp
0,262,-2,Looking for some gift hints from you.,Looking for some gift hints from you.,1/23/2024 9:17:58 AM,86,100,"21454, 21906, 22156, 22284, 22371, 22611, 2262...","LeftShift, L, O, O, K, I, N, G, Space, F, O, R...","LeftShift, L, o, o, k, i, n, g, , f, o, r, ,...","22043, 22051, 22220, 22411, 22500, 22691, 2277...","L, LeftShift, O, O, K, I, N, G, Space, F, O, R..."
1,262,-1,I can't tell you when they'll be back.,I can't tell you when they'll be back.,1/23/2024 9:18:28 AM,63,100,"22442, 22633, 22968, 23041, 23498, 23809, 2394...","LeftShift, I, C, A, Backspace, Backspace, Spac...","LeftShift, I, c, a, Backspace, Backspace, , c...","22769, 22825, 23081, 23131, 23562, 23890, 2407...","I, LeftShift, C, A, Backspace, Backspace, Spac..."
2,262,0,Our forces are ready to come immediately.,Our forces are ready to come immedaitely.,1/23/2024 9:19:04 AM,80,95,"927, 1118, 1311, 1494, 1631, 1718, 1854, 1903,...","LeftShift, LeftShift, O, U, R, Space, F, O, R,...","LeftShift, LeftShift, O, u, r, , f, o, r, c, ...","1071, 1470, 1478, 1655, 1758, 1846, 1926, 1998...","LeftShift, LeftShift, O, U, R, Space, F, O, R,..."
3,262,1,A bad thing has been turned into a good thing.,A bad thing has been turned into a good thing.,1/23/2024 9:19:12 AM,108,100,"586, 857, 970, 1146, 1281, 1346, 1458, 1554, 1...","LeftShift, A, Space, B, A, D, Space, T, H, I, ...","LeftShift, A, , b, a, d, , t, h, i, n, g, ,...","962, 994, 1066, 1211, 1402, 1449, 1601, 1681, ...","LeftShift, A, Space, B, A, D, Space, T, H, I, ..."
4,262,2,Do you want to eat lunch somewhere before?,Do you want to eat lunch somewhere before?,1/23/2024 9:19:19 AM,98,100,"530, 730, 858, 962, 1065, 1130, 1194, 1266, 13...","LeftShift, D, O, Space, Y, O, U, Space, W, A, ...","LeftShift, D, o, , y, o, u, , w, a, n, t, ,...","802, 841, 946, 1114, 1186, 1234, 1313, 1394, 1...","LeftShift, D, O, Space, Y, O, U, Space, W, A, ..."
...,...,...,...,...,...,...,...,...,...,...,...,...
12,s305,10,A bad thing has been turned into a good thing.,A bad thing has been turned into a good thing.,7/11/2024 7:09:58 PM,90,100,"617, 840, 945, 1113, 1233, 1321, 1409, 1505, 1...","LeftShift, A, Space, B, A, D, Space, T, H, I, ...","LeftShift, A, , b, a, d, , t, h, i, n, g, ,...","897, 953, 1040, 1201, 1336, 1409, 1513, 1601, ...","LeftShift, A, Space, B, A, D, Space, T, H, I, ..."
13,s305,11,Our forces are ready to come immediately.,Our forces are ready to come immediately,7/11/2024 7:10:06 PM,67,98,"570, 722, 834, 986, 1034, 1154, 1235, 1355, 15...","LeftShift, O, U, R, Space, F, O, R, C, E, S, S...","LeftShift, O, u, r, , f, o, r, c, e, s, , a,...","762, 882, 929, 1058, 1145, 1250, 1362, 1426, 1...","LeftShift, O, U, R, Space, F, O, R, C, E, S, S..."
14,s305,12,Sunday tickets have been on sale for weeks.,Sunday tickets have been on sale for weeks.,7/11/2024 7:10:16 PM,101,100,"490, 802, 898, 1067, 1107, 1203, 1322, 1386, 1...","LeftShift, S, U, N, D, A, Y, Space, T, I, C, K...","LeftShift, S, u, n, d, a, y, , t, i, c, k, e,...","859, 906, 970, 1147, 1211, 1306, 1443, 1491, 1...","LeftShift, S, U, N, D, A, Y, Space, T, I, C, K..."
15,s305,13,I will need to have my memory refreshed.,I will need to have my memory refreshed.,7/11/2024 7:10:22 PM,94,100,"371, 523, 642, 754, 803, 883, 1019, 1091, 1195...","LeftShift, I, Space, W, I, L, L, Space, N, E, ...","LeftShift, I, , w, i, l, l, , n, e, e, d, ,...","571, 610, 746, 851, 939, 955, 1107, 1187, 1284...","LeftShift, I, Space, W, I, L, L, Space, N, E, ..."
16,s305,14,Let me know if there are any other problems wi...,Let me know if there are any other problems wi...,7/11/2024 7:10:29 PM,106,100,"449, 609, 737, 833, 880, 1017, 1105, 1656, 180...","LeftShift, L, E, T, Space, M, E, Space, K, N, ...","LeftShift, L, e, t, , m, e, , k, n, o, w, ,...","649, 705, 833, 937, 977, 1073, 1201, 1769, 195...","LeftShift, L, E, T, Space, M, E, Space, K, N, ..."

In [62]:
# stripped_keys_1 = ((df['key_resp_1.keys'].str.strip('[,]')).dropna()).str.split(',', expand = True)
stripped_times = ((all_turbo['timeData'].str.strip('[,]')).dropna()).str.split(',', expand = True)
stripped_times

,0,1,2,3,4,5,6,7,8,9,...,78,79,80,81,82,83,84,85,86,87
0,21454,21906,22156,22284,22371,22611,22628,22748,22827,22956,...,None,None,None,None,None,None,None,None,None,None
1,22442,22633,22968,23041,23498,23809,23945,24049,24106,24241,...,None,None,None,None,None,None,None,None,None,None
2,927,1118,1311,1494,1631,1718,1854,1903,2006,2198,...,None,None,None,None,None,None,None,None,None,None
3,586,857,970,1146,1281,1346,1458,1554,1634,1706,...,None,None,None,None,None,None,None,None,None,None
4,530,730,858,962,1065,1130,1194,1266,1361,1426,...,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12,617,840,945,1113,1233,1321,1409,1505,1577,1681,...,None,None,None,None,None,None,None,None,None,None
13,570,722,834,986,1034,1154,1235,1355,1571,1626,...,None,None,None,None,None,None,None,None,None,None
14,490,802,898,1067,1107,1203,1322,1386,1482,1587,...,None,None,None,None,None,None,None,None,None,None
15,371,523,642,754,803,883,1019,1091,1195,1259,...,None,None,None,None,None,None,None,None,None,None
16,449,609,737,833,880,1017,1105,1656,1809,1929,...,None,None,None,None,None,None,None,None,None,None